import assert from "node:assert/strict"
import { test } from "node:test"

import {
  canRetitle,
  retitleFromCompaction,
  setAutoSessionName,
  titleInputFromCompaction,
} from "./index.js"

test("titleInputFromCompaction selects the first compaction text for title generation", () => {
  assert.equal(
    titleInputFromCompaction({
      shortSummary: "\n  ## <b>Fix login</b>  **now**  \nignore the rest",
      summary: "Fallback title",
    }),
    "## <b>Fix login</b>  **now**",
  )
})

test("titleInputFromCompaction falls back to summary text", () => {
  assert.equal(
    titleInputFromCompaction({
      shortSummary: "\n  \n",
      summary: "  Recovered session title  \nignore the rest",
    }),
    "Recovered session title",
  )
})

test("canRetitle only allows untitled-source or auto-titled sessions", () => {
  assert.equal(canRetitle({}), true)
  assert.equal(canRetitle({ titleSource: "auto" }), true)
  assert.equal(canRetitle({ titleSource: "user" }), false)
  assert.equal(canRetitle({ titleSource: "manual" }), false)
})

test("setAutoSessionName uses the auto source and compaction trigger", async () => {
  const calls = []
  const sessionManager = {
    getSessionName: () => "Old title",
    setSessionName: (...args) => calls.push(args),
  }

  await setAutoSessionName(sessionManager, "New title")
  assert.deepEqual(calls, [
    ["New title", "auto", "omp-auto-retitle:session_compact"],
  ])
})

test("setAutoSessionName skips unchanged titles", async () => {
  const sessionManager = {
    getSessionName: () => "Already right",
    setSessionName: () => assert.fail("unchanged title should not be retitled"),
  }

  assert.equal(await setAutoSessionName(sessionManager, "Already right"), false)
})

test("retitleFromCompaction passes compaction text to the injected title generator", async () => {
  const calls = []
  const sessionManager = {
    titleSource: "auto",
    getSessionName: () => "Old title",
    setSessionName: (...args) => calls.push(args),
  }
  const ctx = { model: "fake-model", sessionManager }
  const event = {
    compactionEntry: {
      shortSummary: "\n  Compact this session  \n",
      summary: "Fallback",
    },
  }

  await retitleFromCompaction(event, ctx, {
    generateTitle: async (input, receivedCtx) => {
      assert.equal(input, "Compact this session")
      assert.equal(receivedCtx, ctx)
      return "  **Generated by fake**  "
    },
  })

  assert.deepEqual(calls, [
    ["  **Generated by fake**  ", "auto", "omp-auto-retitle:session_compact"],
  ])
})

test("retitleFromCompaction skips user-titled sessions before title generation", async () => {
  const sessionManager = {
    titleSource: "user",
    setSessionName: () => assert.fail("manual titles should not be retitled"),
  }

  assert.equal(
    await retitleFromCompaction(
      { compactionEntry: { shortSummary: "Should not be used" } },
      { sessionManager },
      {
        generateTitle: () => assert.fail("manual titles should not generate a title"),
      },
    ),
    false,
  )
})
